version: '3.7'

services:

    website:
        container_name: personal_website
        build:
            context: .
            dockerfile: Dockerfile-prod
        volumes: 
            - .:/app
            - /app/node_modules
        ports:
            - 10.136.4.28:80:80