version: '3.7'

services:

    website:
        container_name: personal_website
        build:
            context: .
            dockerfile: Dockerfile-prod
        volumes: 
            - /usr/src/app/data/nginx/main/personal-site:/usr/src/app/dist
 